<?php

/**
 * PluginOcTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOcTransactionTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOcTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOcTransaction');
    }
}