<?php

/**
 * PluginOcConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOcConfigTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOcConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOcConfig');
    }
}