<?php

/**
 * PluginOcApplicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOcApplicationTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOcApplicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOcApplication');
    }
}