<?php

/**
 * PluginOcTicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOcTicketTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOcTicketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOcTicket');
    }
}