<?php

/**
 * PluginOcTimeSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOcTimeSlotTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOcTimeSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOcTimeSlot');
    }
}