<?php

/**
 * PluginOcProfessionalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOcProfessionalTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOcProfessionalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOcProfessional');
    }
}