<?php

/**
 * PluginOcTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOcTokenTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOcTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOcToken');
    }
}